#pragma once
#include <cmath>

//#define PRACTICE_BOT

#ifdef PRACTICE_BOT

// PRACTICE BOT CONSTANTS
#define ODOMETRY_WHEEL_RADIUS 4.5
#define ODOMETRY_TRACK_WIDTH  45.0
#define ODOMETRY_PERP_OFFSET  (-45.0 / 2.0)

#else

// REAL BOT CONSTANTS
#define ODOMETRY_WHEEL_RADIUS 3.0
#define ODOMETRY_TRACK_WIDTH  17.0
#define ODOMETRY_PERP_OFFSET  12.5

#endif

// OTHER DEFINES

#define ODOMETRY_TICKS_PER_CM (8192.0 / (2 * M_PI * ODOMETRY_WHEEL_RADIUS))

#define DRIVETRAIN_FAST_MLT 1.0
#define DRIVETRAIN_SLOW_MLT 0.25
#define DRIVETRAIN_TURN_MLT 0.75

#define EXTEND_MAX_DEGREES 70.0
#define EXTEND_FORW_POWER  1.0
#define EXTEND_BACK_POWER  0.3
#define EXTEND_TICKS_PER_REV (28.0 * 25.0)

#define ROTATE_SERVO_UP   0.85
#define ROTATE_SERVO_MID  0.5
#define ROTATE_SERVO_DOWN 0.03

#define PICKUP_SERVO_CLOSED 0.45
#define PICKUP_SERVO_OPEN   0.0

#define BASKET_SERVO_COLLECT 0.5
#define BASKET_SERVO_SCORE   0.1
#define BASKET_SERVO_BALANCE 0.35

#define LIFT_HOLD_POWER 0.2
#define LIFT_UP_MLT     1.0
#define LIFT_DOWN_MLT   0.75

#define LIFT_UP_POSITION   45.0
#define LIFT_TICKS_PER_REV (28.0 * 25.0)
#define LIFT_GEAR_RADIUS   2.0
#define LIFT_TICKS_PER_CM  (LIFT_TICKS_PER_REV / (2 * M_PI * LIFT_GEAR_RADIUS))

#define AUTON_PID_X_THRESHOLD  5.0
#define AUTON_PID_Y_THRESHOLD  5.0
#define AUTON_PID_TH_THRESHOLD 2.0