#pragma once

#define ROTATE_SERVO_UP   0.85
#define ROTATE_SERVO_MID 0.5
#define ROTATE_SERVO_DOWN 0.1

#define PICKUP_SERVO_CLOSED 0.0
#define PICKUP_SERVO_OPEN   0.4

#define BASKET_SERVO_COLLECT 0.5
#define BASKET_SERVO_SCORE   0.1
#define BASKET_SERVO_BALANCE 0.35

#define EXTEND_HOLD_POWER 0.5
#define LIFT_HOLD_POWER 0.2
